// Default data for new services
export const DEFAULT_SERVICE_DATA: any = {
  id: 0,
  slug: "",
  category_id: 0,
  price: "",
  price_before_discount: "",
  type: "one_time",
  order: 0,
  is_active: true,
  deleted_images: [],
  testimonials_images: [],
  hero_section: {
    badge_ar: "",
    badge_en: "",
    title_ar: "",
    title_en: "",
    subtitle_ar: "",
    subtitle_en: "",
    description_ar: "",
    description_en: "",
    hero_image: "",
    background_image: "",
  },
  gallery_images: [],
  problem_section: {
    title_ar: "",
    title_en: "",
    subtitle_ar: "",
    subtitle_en: "",
    items: [],
  },
  solution_section: {
    title_ar: "",
    title_en: "",
    cta_text_ar: "",
    cta_text_en: "",
    features: [],
  },
  stats: [],
  testimonials: [],
  cta_section: {
    cta_title_ar: "",
    cta_title_en: "",
    cta_subtitle_ar: "",
    cta_subtitle_en: "",
    cta_button1_ar: "",
    cta_button1_en: "",
    cta_button2_ar: "",
    cta_button2_en: "",
  },
};
