const countries = [
  { code: "EG", name: "مصر", name_en: "Egypt" },
  { code: "SA", name: "السعودية", name_en: "Saudi Arabia" },
  { code: "AE", name: "الإمارات", name_en: "United Arab Emirates" },
  { code: "KW", name: "الكويت", name_en: "Kuwait" },
  { code: "QA", name: "قطر", name_en: "Qatar" },
  { code: "OM", name: "عُمان", name_en: "Oman" },
  { code: "BH", name: "البحرين", name_en: "Bahrain" },
  { code: "JO", name: "الأردن", name_en: "Jordan" },
  { code: "IQ", name: "العراق", name_en: "Iraq" },
  { code: "SY", name: "سوريا", name_en: "Syria" },
  { code: "LB", name: "لبنان", name_en: "Lebanon" },
  { code: "MA", name: "المغرب", name_en: "Morocco" },
  { code: "TN", name: "تونس", name_en: "Tunisia" },
  { code: "DZ", name: "الجزائر", name_en: "Algeria" },
  { code: "YE", name: "اليمن", name_en: "Yemen" },
  { code: "SD", name: "السودان", name_en: "Sudan" },
  { code: "LY", name: "ليبيا", name_en: "Libya" },
  { code: "PS", name: "فلسطين", name_en: "Palestine" },
  { code: "TR", name: "تركيا", name_en: "Turkey" },
  { code: "US", name: "الولايات المتحدة", name_en: "United States" },
  { code: "GB", name: "المملكة المتحدة", name_en: "United Kingdom" },
  { code: "FR", name: "فرنسا", name_en: "France" },
  { code: "DE", name: "ألمانيا", name_en: "Germany" },
  { code: "IT", name: "إيطاليا", name_en: "Italy" },
  { code: "ES", name: "إسبانيا", name_en: "Spain" },
  { code: "CA", name: "كندا", name_en: "Canada" },
  { code: "AU", name: "أستراليا", name_en: "Australia" },
  { code: "RU", name: "روسيا", name_en: "Russia" },
  { code: "CN", name: "الصين", name_en: "China" },
  { code: "JP", name: "اليابان", name_en: "Japan" },
  { code: "IN", name: "الهند", name_en: "India" },
  { code: "BR", name: "البرازيل", name_en: "Brazil" },
  { code: "ZA", name: "جنوب أفريقيا", name_en: "South Africa" },
  { code: "KR", name: "كوريا الجنوبية", name_en: "South Korea" },
  { code: "AR", name: "الأرجنتين", name_en: "Argentina" },
  { code: "MX", name: "المكسيك", name_en: "Mexico" },
  { code: "SE", name: "السويد", name_en: "Sweden" },
  { code: "NL", name: "هولندا", name_en: "Netherlands" },
  { code: "CH", name: "سويسرا", name_en: "Switzerland" },
];

export default countries;
